language: nix
script:
- nix-env -iA cachix
- echo "trusted-users = root ${USER}" | sudo tee -a /etc/nix/nix.conf || true
- sudo pkill nix-daemon || true
- cachix use mafo
- nix-build -A myPackage -o result-wsjtx-to-mqtt --argstr compiler $COMPILER
# - nix-shell --run 'cabal new-build'
after_success:
- cachix push mafo ./result-wsjtx-to-mqtt
matrix:
  include:
  - name: GHC 863
    env: COMPILER="ghc863"
